---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - git

- name: Configure NGINX
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart NGINX
